import type { Asset } from './AssetSidebar';

const now = Date.now();

export const mockAssets: Asset[] = [
  {
    id: '1',
    title: 'Q4 Financial Report',
    kind: 'pdf',
    updatedAtMs: now - 5 * 60000,
    tags: ['finance', 'quarterly'],
    description: 'Q4 summary.',
  },
  {
    id: '2',
    title: 'Meeting Notes - Product Sync',
    kind: 'note',
    updatedAtMs: now - 15 * 60000,
    tags: ['meeting', 'product'],
    description: 'Sync notes.',
  },
  {
    id: '3',
    title: 'Tech Industry Update',
    kind: 'news',
    updatedAtMs: now - 30 * 60000,
    tags: ['tech', 'news'],
    description: 'Tech news.',
  },
  {
    id: '4',
    title: 'Employee Handbook 2024',
    kind: 'pdf',
    updatedAtMs: now - 60 * 60000,
    tags: ['hr', 'policy'],
    description: 'HR policies.',
  },
  {
    id: '5',
    title: 'Sprint Retrospective',
    kind: 'note',
    updatedAtMs: now - 2 * 60 * 60000,
    tags: ['agile', 'team'],
    description: 'Retro items.',
  },
  {
    id: '6',
    title: 'Market Analysis Report',
    kind: 'pdf',
    updatedAtMs: now - 3 * 60 * 60000,
    tags: ['market', 'analysis'],
    description: 'Market data.',
  },
  {
    id: '7',
    title: 'Breaking: AI Advances',
    kind: 'news',
    updatedAtMs: now - 4 * 60 * 60000,
    tags: ['ai', 'breaking'],
    description: 'AI update.',
  },
  {
    id: '8',
    title: 'Design System Guidelines',
    kind: 'pdf',
    updatedAtMs: now - 5 * 60 * 60000,
    tags: ['design', 'ux'],
    description: 'Design docs.',
  },
  {
    id: '9',
    title: 'Client Call Summary',
    kind: 'note',
    updatedAtMs: now - 6 * 60 * 60000,
    tags: ['client', 'sales'],
    description: 'Call notes.',
  },
  {
    id: '10',
    title: 'Startup Funding News',
    kind: 'news',
    updatedAtMs: now - 7 * 60 * 60000,
    tags: ['startup', 'funding'],
    description: 'Funding news.',
  },
  {
    id: '11',
    title: 'API Documentation',
    kind: 'pdf',
    updatedAtMs: now - 8 * 60 * 60000,
    tags: ['api', 'dev'],
    description: 'API docs.',
  },
  {
    id: '12',
    title: 'Weekly Standup Notes',
    kind: 'note',
    updatedAtMs: now - 9 * 60 * 60000,
    tags: ['standup', 'weekly'],
    description: 'Standup log.',
  },
  {
    id: '13',
    title: 'Crypto Market Update',
    kind: 'news',
    updatedAtMs: now - 10 * 60 * 60000,
    tags: ['crypto', 'market'],
    description: 'Crypto news.',
  },
  {
    id: '14',
    title: 'Budget Proposal 2025',
    kind: 'pdf',
    updatedAtMs: now - 11 * 60 * 60000,
    tags: ['budget', 'finance'],
    description: 'Budget plan.',
  },
  {
    id: '15',
    title: 'Brainstorm Session Ideas',
    kind: 'note',
    updatedAtMs: now - 12 * 60 * 60000,
    tags: ['ideas', 'brainstorm'],
    description: 'Ideas list.',
  },
  {
    id: '16',
    title: 'Climate Report Summary',
    kind: 'news',
    updatedAtMs: now - 13 * 60 * 60000,
    tags: ['climate', 'environment'],
    description: 'Climate info.',
  },
  {
    id: '17',
    title: 'Security Audit Results',
    kind: 'pdf',
    updatedAtMs: now - 14 * 60 * 60000,
    tags: ['security', 'audit'],
    description: 'Audit report.',
  },
  {
    id: '18',
    title: 'Interview Feedback',
    kind: 'note',
    updatedAtMs: now - 15 * 60 * 60000,
    tags: ['hiring', 'feedback'],
    description: 'Feedback notes.',
  },
  {
    id: '19',
    title: 'Sports Headlines Today',
    kind: 'news',
    updatedAtMs: now - 16 * 60 * 60000,
    tags: ['sports', 'headlines'],
    description: 'Sports news.',
  },
  {
    id: '20',
    title: 'Compliance Checklist',
    kind: 'pdf',
    updatedAtMs: now - 17 * 60 * 60000,
    tags: ['compliance', 'legal'],
    description: 'Checklist.',
  },
];
